services:
  grammatomy-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grammatomy-api
    restart: unless-stopped
    ports:
      - "7860:7860" # Puerto definido en tu Dockerfile (Uvicorn)
    volumes:
      # Montamos el código para Hot-Reloading (desarrollo en vivo)
      - ./src/core:/app/src/core
      - ./src/api:/app/src/api
      - ./models:/app/models
    # Sobrescribimos el comando para activar 'reload'.
    # Uvicorn detectará tus cambios en local y reiniciará el servidor automáticamente.
    command: uvicorn src.api.app.main:app --host 0.0.0.0 --port 7860 --reload
    networks:
      - grammatomy-net

networks:
  grammatomy-net:
    driver: bridge
    name: grammatomy-net