[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "grammatomy-workspace"
version = "0.1.0"
description = "Monorepo for the Grammatomy Project"
authors = [{name = "Wayfarer", email = "wayfarer@mnemosyne.net"}]
readme = "Readme.md"
requires-python = ">=3.10"
# Dependencies are now managed in their respective sub-projects (src/core, src/api, etc.)

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "mypy",
    "pylint",
    "httpx"
]

[tool.pylint.main]
source-roots = ["src/core", "src/api", "src/studio"]
extension-pkg-allow-list = ["PyQt6"]

[tool.pylint."messages control"]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "too-few-public-methods",
]
good-names = [
    "e", "i", "j", "k", "v", # common loop variables
    "ex", # common exception variable
    "fp", # file pointer
    "wheelEvent",
    "itemChange",
    "mouseMoveEvent",
    "mouseReleaseEvent",
    "contextMenuEvent",
]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')"
]
filterwarnings = [
    "ignore:.*SwigPy.*:DeprecationWarning",
    "ignore:.*swigvarlink.*:DeprecationWarning",
    "ignore:.*torch_struct.*:UserWarning"
]