sonar.projectKey=grammatomy-workspace
sonar.projectName=Grammatomy
sonar.projectVersion=0.1.0

# Fuentes y Tests
sonar.sources=src
sonar.tests=tests

# Configuración de Python
sonar.python.version=3.10

# Exclusiones (Vital para no analizar librerías o metadatos)
sonar.exclusions=**/*.egg-info/**, **/build/**, **/dist/**, **/__pycache__/**, **/.mnemosyne/**

# Opcional: Si usas coverage
# sonar.python.coverage.reportPaths=coverage.xml