# Source of Truth for UI Tables and Graphviz Tooltips
TAG_MAP = {
    "Phrasal": {
        "ADJP": "Adjective Phrase",
        "ADVP": "Adverb Phrase",
        "CONJP": "Conjunction Phrase",
        "FRAG": "Fragment",
        "INTJ": "Interjection",
        "LST": "List marker",
        "Morfema-pronominal": "Pronominal Morpheme",
        "NAC": "Not A Constituent",
        "NP": "Noun Phrase",
        "NX": "Head of a complex NP",
        "PP": "Prepositional Phrase",
        "PRN": "Parenthetical",
        "PRT": "Particle",
        "QP": "Quantifier Phrase",
        "ROOT": "Root Node",
        "RRC": "Reduced Relative Clause",
        "S": "Simple Declarative Clause",
        "SBAR": "Clause introduced by a subordinating conjunction",
        "SBARQ": "Direct question introduced by a wh-word",
        "SINV": "Inverted declarative sentence",
        "SQ": "Inverted yes/no question",
        "Sentence": "Sentence / Oración",
        "TOP": "Top Node",
        "UCP": "Unlike Coordinated Phrase",
        "VP": "Verb Phrase",
        "WHADJP": "Wh-adjective Phrase",
        "WHADVP": "Wh-adverb Phrase",
        "WHNP": "Wh-noun Phrase",
        "WHPP": "Wh-prepositional Phrase",
        "grup.a": "Adjectival Group (AnCora)",
        "grup.adv": "Adverbial Group (AnCora)",
        "grup.nom": "Nominal Group (AnCora)",
        "grup.prep": "Prepositional Group (AnCora)",
        "grup.verb": "Verbal Group (AnCora)",
        "inc": "Included/Parenthetical",
        "morf": "Morpheme (Gender/Number)",
        "s.a": "Adjective Phrase (Sintagma Adjetival)",
        "s.adv": "Adverb Phrase (Sintagma Adverbial)",
        "sadv": "Adverb Phrase (Sintagma Adverbial)",
        "sentence": "Sentence / Oración",
        "sn": "Noun Phrase (Sintagma Nominal)",
        "sp": "Prepositional Phrase (Sintagma Preposicional)",
        "spec": "Specifier",
        "sv": "Verb Phrase (Sintagma Verbal)"
    },
    "POS": {
        "ADJ": "Adjective",
        "ADP": "Adposition (Preposition)",
        "ADV": "Adverb",
        "AUX": "Auxiliary verb",
        "CC": "Coordinating conjunction",
        "CCONJ": "Coordinating conjunction",
        "CD": "Cardinal number",
        "DET": "Determiner",
        "DT": "Determiner",
        "EX": "Existential there",
        "FW": "Foreign word",
        "IN": "Preposition or subordinating conjunction",
        "INTJ": "Interjection",
        "JJ": "Adjective",
        "JJR": "Adjective, comparative",
        "JJS": "Adjective, superlative",
        "LS": "List item marker",
        "MD": "Modal",
        "NN": "Noun, singular or mass",
        "NNP": "Proper noun, singular",
        "NNPS": "Proper noun, plural",
        "NNS": "Noun, plural",
        "NOUN": "Noun",
        "NUM": "Numeral",
        "PART": "Particle",
        "PDT": "Predeterminer",
        "POS": "Possessive ending",
        "PREP": "Preposition",
        "PRON": "Pronoun",
        "PROPN": "Proper noun",
        "PRP": "Personal pronoun",
        "PRP$": "Possessive pronoun",
        "PUNCT": "Punctuation",
        "RB": "Adverb",
        "RBR": "Adverb, comparative",
        "RBS": "Adverb, superlative",
        "RP": "Particle",
        "SCONJ": "Subordinating conjunction",
        "SYM": "Symbol",
        "TO": "to",
        "UH": "Interjection",
        "VB": "Verb, base form",
        "VBD": "Verb, past tense",
        "VBG": "Verb, gerund or present participle",
        "VBN": "Verb, past participle",
        "VBP": "Verb, non-3rd person singular present",
        "VBZ": "Verb, 3rd person singular present",
        "VERB": "Verb",
        "WDT": "Wh-determiner",
        "WP": "Wh-pronoun",
        "WP$": "Possessive wh-pronoun",
        "WRB": "Wh-adverb",
        "X": "Other",
        "gerundi": "Gerund (Verb)",
        "infinitiu": "Infinitive (Verb)",
        "neg": "Negation",
        "participi": "Participle (Verb)",
        "prep": "Preposition",
        "relatiu": "Relative (Pronoun/Adverb)"
    }
}