[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "grammatomy-service"
version = "0.1.0"
description = "RESTful API Layer for Grammatomy"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-multipart",
    # En desarrollo local, instalaremos el core en modo editable (-e ../core)
    # En producción, esto sería una dependencia de paquete real.
]

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
grammatomy-server = "app.main:start"

[tool.pyright]
# Resolve imports from the 'src' root (located two levels up)
extraPaths = ["../../"]
include = ["."]
[tool.pylint.format]
max-line-length = 120
